<a href="https://colab.research.google.com/github/samadhan1234567/dl/blob/main/dibeties.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv("/content/diabetes.csv")

In [ ]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [ ]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [ ]:
x=df.iloc[:,:-1]
y=df['Outcome'].values

In [ ]:
x

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x=sc.fit_transform(x)

In [ ]:
x

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [ ]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.30,random_state=1)

In [ ]:
import tensorflow as tf
from tensorflow.keras import Sequential # it is used to build NN
from tensorflow.keras.layers import Dense # it is used to add hidden layers
from sklearn.metrics import classification_report #evaulation


In [ ]:
ann=Sequential()

In [ ]:
ann.add(Dense(units=12,activation="relu")) #HL
ann.add(Dense(units=1,activation="sigmoid"))

In [ ]:
ann.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

In [ ]:
ann.fit(xtrain,ytrain,epochs=100,batch_size=32)

Epoch 1/100
17/17 [==============================] - 1s 2ms/step - loss: 0.6932 - accuracy: 0.6276
Epoch 2/100
17/17 [==============================] - 0s 2ms/step - loss: 0.6708 - accuracy: 0.6443
Epoch 3/100
17/17 [==============================] - 0s 2ms/step - loss: 0.6503 - accuracy: 0.6480
Epoch 4/100
17/17 [==============================] - 0s 2ms/step - loss: 0.6338 - accuracy: 0.6443
Epoch 5/100
17/17 [==============================] - 0s 2ms/step - loss: 0.6187 - accuracy: 0.6536
Epoch 6/100
17/17 [==============================] - 0s 2ms/step - loss: 0.6044 - accuracy: 0.6499
Epoch 7/100
17/17 [==============================] - 0s 2ms/step - loss: 0.5922 - accuracy: 0.6555
Epoch 8/100
17/17 [==============================] - 0s 2ms/step - loss: 0.5812 - accuracy: 0.6611
Epoch 9/100
17/17 [==============================] - 0s 2ms/step - loss: 0.5705 - accuracy: 0.6760
Epoch 10/100
17/17 [==============================] - 0s 2ms/step - loss: 0.5611 - accuracy: 0.6872
Epoch 11/

In [ ]:
ypred=ann.predict(xtest)

8/8 [==============================] - 0s 2ms/step


In [ ]:
ypred

array([[0.47908324],
       [0.2709383 ],
       [0.09795218],
       [0.07685128],
       [0.1846031 ],
       [0.20496146],
       [0.4599167 ],
       [0.06030441],
       [0.14608003],
       [0.13390525],
       [0.50539947],
       [0.13273995],
       [0.93710434],
       [0.6215966 ],
       [0.02068013],
       [0.6817622 ],
       [0.35272244],
       [0.43638456],
       [0.08345293],
       [0.10493216],
       [0.44632503],
       [0.20469594],
       [0.85240835],
       [0.2743407 ],
       [0.03291193],
       [0.5122051 ],
       [0.25257638],
       [0.7979833 ],
       [0.06969015],
       [0.49585626],
       [0.32034397],
       [0.44416615],
       [0.02795216],
       [0.65145063],
       [0.12909068],
       [0.71822625],
       [0.04465744],
       [0.21776718],
       [0.0781239 ],
       [0.4451154 ],
       [0.16704571],
       [0.04519963],
       [0.01600403],
       [0.4846284 ],
       [0.04094328],
       [0.00434937],
       [0.6667265 ],
       [0.924

In [ ]:
ypred=np.where(ypred>0.5,1,0)
ypred


array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
    

In [ ]:
print(classification_report(ytest,ypred))

              precision    recall  f1-score   support

           0       0.82      0.89      0.85       146
           1       0.78      0.66      0.71        85

    accuracy                           0.81       231
   macro avg       0.80      0.77      0.78       231
weighted avg       0.80      0.81      0.80       231

